FeuerwehrApp/Controllers/AtemschutzController.cs
using FeuerwehrApp.Data;
using FeuerwehrApp.Migrations;
using FeuerwehrApp.Models;
using Microsoft.AspNetCore.Mvc;

namespace FeuerwehrApp.Controllers
{
    public class AtemschutzController : Controller
    {
        private readonly ApplicationDbContext _context;
        public AtemschutzController(ApplicationDbContext context)
        {
            _context = context;
        }
        public IActionResult Overview()
        {
            var masken = _context.Masken.OrderBy(m => m.ExpiringDate).ToList();
            var geraete = _context.Geraete.OrderBy(m => m.ExpiringDate).ToList();
            var agt = _context.AGT.OrderBy(m => m.ExpiringDates.Min()).ToList();
            var fs = _context.DrivingLicense.OrderBy(m => m.ExpiringDate).ToList();
            var fm = _context.Feuerwehrmann.OrderBy(m => m.preName).ToList();

            var viewModel = new OverviewViewModel
            {
                Atemschutzmasken = masken,
                Atemschutzgeraete = geraete,
                AGT = agt,
                DrivingLicenses = fs,
            };

            return View(viewModel);
        }

        public IActionResult CreateEditMaske()
        {
            return View();
        }
        [HttpPost]
        public IActionResult CreateEditMaske(Atemschutzmaske maske)
        {
            maske.ExpiringDate = maske.CheckDate.AddMonths(6);
            _context.Masken.Add(maske);
            _context.SaveChanges();
            return RedirectToAction(nameof(Overview));
        }
        public IActionResult DeleteMaske(int id)
        {
            var maske = _context.Masken.Find(id);
            if (maske != null)
            {
                _context.Masken.Remove(maske);
                _context.SaveChanges();
            }
            return RedirectToAction(nameof(Overview));
        }

        public IActionResult CreateEditGeraet()
        {
            return View();
        }
        [HttpPost]
        public IActionResult CreateEditGeraet(Atemschutzgeraet geraet)
        {
            geraet.ExpiringDate = geraet.CheckDate.AddMonths(6);
            _context.Geraete.Add(geraet);
            _context.SaveChanges();
            return RedirectToAction(nameof(Overview));
        }
        public IActionResult DeleteGeraet(int id)
        {
            var geraet = _context.Geraete.Find(id);
            if (geraet != null)
            {
                _context.Geraete.Remove(geraet);
                _context.SaveChanges();
            }
            return RedirectToAction(nameof(Overview));
        }

        public IActionResult CreateEditAGT(int id)
        {
            if (id != 0)
            {
                var agt = _context.AGT.Find(id);
                return View(agt);

            }
            return View();
        }
        [HttpPost]
        public IActionResult CreateEditAGT(Geraetetraeger agt)
        {

            if (agt.IsU50 = agt.CalculateAge(agt.birthDate))
            {
                agt.G26Expiring = agt.G26.AddYears(3).AddDays(-1);
            }
            else
            {
                agt.G26Expiring = agt.G26.AddYears(1).AddDays(-1);
            }
            agt.BelastungExpiring = agt.Belastung.AddYears(1).AddDays(-1);
            agt.EinsatzExpiring = agt.Einsatz.AddYears(1).AddDays(-1);
            agt.UnterweisungExpiring = agt.Unterweisung.AddYears(1).AddDays(-1);


            List<DateTime> ExpiringDates = new List<DateTime>
            {
                agt.G26Expiring,
                agt.BelastungExpiring,
                agt.EinsatzExpiring,
                agt.UnterweisungExpiring,
            };
            if (agt.Id == null)
            {
                _context.AGT.Add(agt);
            }
            else
            {
                _context.AGT.Update(agt);
            }
            agt.ExpiringDates = ExpiringDates;
            _context.SaveChanges();
            return RedirectToAction(nameof(Overview));
        }
        public IActionResult DeleteAGT(int id)
        {
            var agt = _context.AGT.Find(id);
            if (agt != null)
            {
                _context.AGT.Remove(agt);
                _context.SaveChanges();
            }
            return RedirectToAction(nameof(Overview));
        }
        public IActionResult DetailsAGT()
        {
            var geraetetraeger = _context.AGT.ToList();
            var viewModel = new OverviewViewModel
            {
                AGT = geraetetraeger,
            };
            return View(viewModel);
        }

        public IActionResult CreateEditLicense(int id)
        {
            if (id != 0)
            {
                var fs = _context.DrivingLicense.Find(id);
                return View(fs);
            }
            return View();
        }
        [HttpPost]
        public IActionResult CreateEditLicense(Models.Fuehrerschein fs)
        {
            if (fs.Id == null)
            {
                fs.CheckDate = DateTime.Today;
                _context.DrivingLicense.Add(fs);
            }
            else
            {
                _context.DrivingLicense.Update(fs);
            }

            _context.SaveChanges();
            return RedirectToAction(nameof(Overview));
        }
        public IActionResult DeleteLicense(int id)
        {
            var fs = _context.DrivingLicense.Find(id);
            if (fs != null)
            {
                _context.DrivingLicense.Remove(fs);
                _context.SaveChanges();
            }
            return RedirectToAction(nameof(Overview));
        }
        public IActionResult CheckLicense(int id)
        {
            var fs = _context.DrivingLicense.Find(id);
            {
                if (fs != null)
                {
                    fs.CheckDate = DateTime.Today;
                    _context.Update(fs);
                    _context.SaveChanges();
                }
                return RedirectToAction(nameof(Overview));
            }
        }

        public IActionResult CreateEditFM()
        {
            var dienstgrade = new Dictionary<int, string>
            {
                { 1, "Feuerwehrmannanwärter/in" },
                { 2, "Feuerwehrmann/-frau" },
                { 3, "Oberfeuerwehrmann/-frau" },
                { 4, "Hauptfeuerwehrmann/-frau" },
                { 5, "Löschmeister/in" },
                { 6, "Oberlöschmeister/in" },
                { 7, "Hauptlöschmeister/in" },
                { 8, "Brandmeister/in" },
                { 9, "Oberbrandmeister/in" },
                { 10, "Hauptbrandmeister/in" },
            };
            ViewBag.Dienstgrade = dienstgrade;
            return View();
        }
        [HttpPost]
        public IActionResult CreateEditFM(Models.Feuerwehrmann fm)
        {
            
            if (fm.Id == 0)
            {
                _context.Feuerwehrmann.Add(fm);
            }
            else 
            {
                _context.Feuerwehrmann.Update(fm);
            }
            _context.SaveChanges();

            return RedirectToAction(nameof(Overview));

        }
        public IActionResult DetailsFM() 
        {
            var dienstgrade = new Dictionary<int, string>
            {
                { 1, "Feuerwehrmannanwärter/in" },
                { 2, "Feuerwehrmann/-frau" },
                { 3, "Oberfeuerwehrmann/-frau" },
                { 4, "Hauptfeuerwehrmann/-frau" },
                { 5, "Löschmeister/in" },
                { 6, "Oberlöschmeister/in" },
                { 7, "Hauptlöschmeister/in" },
                { 8, "Brandmeister/in" },
                { 9, "Oberbrandmeister/in" },
                { 10, "Hauptbrandmeister/in" },
            };
            ViewBag.Dienstgrade = dienstgrade;
            var feuerwehrmann = _context.Feuerwehrmann.ToList();
            var viewModel = new OverviewViewModel
            {
                Feuerwehrmaenner = feuerwehrmann,
            };
            return View(viewModel); 
        }
        public IActionResult FMBefoerdern(int id)
        {
            var fm = _context.Feuerwehrmann.Find(id);
            fm.dienstGrad = fm.FMBefoerdern(fm.dienstGrad);
            _context.Update(fm);
            _context.SaveChanges();

            return RedirectToAction(nameof(DetailsFM));
        }
        public IActionResult FMDegradieren(int id) 
        {
            var fm = _context.Feuerwehrmann.Find(id);
            fm.dienstGrad = fm.FMDegradieren(fm.dienstGrad);
            _context.Update(fm);
            _context.SaveChanges();

            return RedirectToAction(nameof(DetailsFM));
        }
    }
}

FeuerwehrApp/Views/Atemschutz/CreateEditAGT.cshtml
@model Geraetetraeger

<h1>Maske anlegen oder bearbeiten</h1>
<form method="post" asp-action="CreateEditAGT" asp-controller="Atemschutz">
    <div>
        <input hidden type="number" class="form-control" asp-for="Id" />
    </div>
    <div>
        <label class="form-label" asp-for="preName">Vorname:</label>
        <input type="text" class="form-control" asp-for="preName" />
        <label class="form-label" asp-for="lastName">Nachname:</label>
        <input type="text" class="form-control" asp-for="lastName" />
    </div>
    <div>
        <label class="form-label" asp-for="G26">G26 Untersuchung am:</label>
        <input type="date" class="form-control" asp-for="G26" />
    </div>
    <div>
        <label class="form-label" asp-for="birthDate">Geburtsdatum:</label>
        <input type="date" class="form-control" asp-for="birthDate" />
    </div>
    <div>
        <label class="form-label" asp-for="Belastung">Streckendurchgang am:</label>
        <input type="date" class="form-control" asp-for="Belastung" />
    </div>
    <div>
        <label class="form-label" asp-for="Unterweisung">Theoretische Unterweisung am:</label>
        <input type="date" class="form-control" asp-for="Unterweisung" />
    </div>
    <div>
        <label class="form-label" asp-for="Einsatz">Übung/Einsatz am:</label>
        <input type="date" class="form-control" asp-for="Einsatz" />
    </div>
    <button type="submit" class="btn btn-primary mt-2">
        Speichern
    </button>
</form>



@section Scripts
{
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

FeuerwehrApp/Views/Atemschutz/CreateEditFM.cshtml
@model Feuerwehrmann

<h1>Feuerwehrmann anlegen oder bearbeiten</h1>
<form method="post" asp-action="CreateEditFM" asp-controller="Atemschutz">
    <div>
        <input hidden type="number" class="form-control" asp-for="Id" />
    </div>
    <div>
        <label class="form-label" asp-for="preName">Vorname:</label>
        <input type="text" class="form-control" asp-for="preName" />
        <label class="form-label" asp-for="lastName">Nachname:</label>
        <input type="text" class="form-control" asp-for="lastName" />
    </div>
    <div>
        <label class="form-label" asp-for="Geburtsdatum">Geburtsdatum am:</label>
        <input type="date" class="form-control" asp-for="Geburtsdatum" />
    </div>

    <div>
        <label class="form-label" asp-for="dienstGrad">Dienstgrad:</label>
        <select class="form-label" asp-for="dienstGrad">
            @foreach (var option in (Dictionary<int, string>)ViewBag.Dienstgrade)
            {
                <option value="@option.Key">@option.Value</option>
            }
        </select>
    </div>
    <button type="submit" class="btn btn-primary mt-2">
        Speichern
    </button>
</form>



@section Scripts
{
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

FeuerwehrApp/Views/Atemschutz/CreateEditGeraet.cshtml
@model Atemschutzgeraet

<h1>Neues Atemschutzgerät anlegen</h1>
<form method="post" asp-action="CreateEditGeraet" asp-controller="Atemschutz">
    <div>
        <input hidden type="number" class="form-control" asp-for="Id" />
    </div>
    <div>
        <label class="form-label" asp-for="Number">Gerätenummer neu:</label>
        <input type="number" class="form-control" asp-for="Number" />
    </div>
    <div>
        <label class="form-label" asp-for="CheckDate">Gerät geprüft am:</label>
        <input type="date" class="form-control" asp-for="CheckDate" />
    </div>
    
    <button type="submit" class="btn btn-primary mt-2">
        Speichern
    </button>
</form>



@section Scripts
{
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

FeuerwehrApp/Views/Atemschutz/CreateEditLicense.cshtml
@model Fuehrerschein

<h1>Fahrer anlegen oder bearbeiten</h1>
<form method="post" asp-action="CreateEditLicense" asp-controller="Atemschutz">
    <div>
        <input hidden type="number" class="form-control" asp-for="Id" />
    </div>
    <div>
        <label class="form-label" asp-for="preName">Vorname:</label>
        <input type="text" class="form-control" asp-for="preName" />
        <label class="form-label" asp-for="lastName">Nachname:</label>
        <input type="text" class="form-control" asp-for="lastName" />
    </div>
    <div>
        <label class="form-label" asp-for="ExpiringDate">Ablaufdatum am:</label>
        <input type="date" class="form-control" asp-for="ExpiringDate" />
    </div>
    <div>
        <label class="form-label" asp-for="FSKlasse">Führerscheinklasse</label>
        <select class="form-label" asp-for="FSKlasse">
            <option>B</option>
            <option>C</option>
            <option>CE</option>
        </select>
    </div>
    <div>
        <label class="form-label" asp-for="Usage">Verwendung</label>
        <select class="form-label" asp-for="Usage">
            <option>Einsatzfahrer</option>
            <option>Jugendfeuerwehr</option>
            <option>zbV</option>
        </select>
    </div>
    
    <button type="submit" class="btn btn-primary mt-2">
        Speichern
    </button>
</form>



@section Scripts
{
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

FeuerwehrApp/Views/Atemschutz/CreateEditMaske.cshtml
@model Atemschutzmaske

<h1>Maske anlegen oder bearbeiten</h1>
<form method="post" asp-action="CreateEditMaske" asp-controller="Atemschutz">
    <div>
        <input hidden type="number" class="form-control" asp-for="Id" />
    </div>
    <div>
        <label class="form-label" asp-for="Number">Maskennummer neu:</label>
        <input type="number" class="form-control" asp-for="Number" />
    </div>
    <div>
        <label class="form-label" asp-for="CheckDate" >Maske geprüft am:</label>
        <input type="date" class="form-control" asp-for="CheckDate" />
    </div>
    <div>
        <label class="form-label" asp-for="IsPersonalized">Maske personalisiert?</label>
        <input type="checkbox" asp-for="IsPersonalized" class="form-check-input" />

    </div>
    <div>
        <label class="form-label" asp-for="StoragePlace">Lagerort:</label>
        <select class="form-label" asp-for="StoragePlace">
            <option>Im Fahrzeug</option>
            <option>Spind</option>
        </select>
    </div>
    <button type="submit" class="btn btn-primary mt-2">
        Speichern
    </button>
</form>



@section Scripts
{
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

FeuerwehrApp/Views/Atemschutz/DetailsAGT.cshtml
@model OverviewViewModel

<div>
    
    <h2>Übersicht der Atemschutzgeräteträger</h2>
    <div class="row">
        <div class="col-md-3">
            <img src="~/Images/agt.png" alt="Geräteträger" class="img-fluid" />
        </div>
        <div class="col-md-9" id="tblAGT">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Vorname</th>
                        <th>Tauglich?</th>
                        <th>G26</th>
                        <th>Streckendurchgang</th>
                        <th>Einsatz/Übung</th>
                        <th>Unterweisung</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var agt in Model.AGT)
                    {
                        <tr>
                            <td>@agt.lastName</td>
                            <td>@agt.preName</td>
                            <td>
                                @if (agt.ExpiringDates.Min() >= DateTime.Now)
                                {

                                    <span class="fa fa-check-circle" style="expiring-green">Ja</span>
                                }
                                else
                                {
                                    <span class="fa fa-times-circle" style="expiring-red">Nein</span>
                                }
                            </td>
                            <td>@agt.G26Expiring.ToString("dd/MM/yyyy")</td>
                            <td>@agt.BelastungExpiring.ToString("dd/MM/yyyy")</td>
                            <td>@agt.EinsatzExpiring.ToString("dd/MM/yyyy")</td>
                            <td>@agt.UnterweisungExpiring.ToString("dd/MM/yyyy")</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

FeuerwehrApp/Views/Atemschutz/DetailsFM.cshtml
@model OverviewViewModel

<div>

    <h2>Übersicht der Feuerwehrleute</h2>
    <div class="row">
        <div class="col-md-3">
            <img src="~/Images/aufschiebeschlaufen-hessen-16849-0.jpg" alt="Geräteträger" class="img-fluid" />
        </div>
        <div class="col-md-9" id="tblFeuerwehrleute">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Vorname</th>
                        <th>Geburtsdatum</th>
                        <th>Dienstgrad</th>
                        <th>Beförderung</th>

                    </tr>
                </thead>
                <tbody>
                    @foreach (var feuerwehrmann in Model.Feuerwehrmaenner)
                    {
                        <tr class="justify-content-center">
                            <td>@feuerwehrmann.lastName</td>
                            <td>@feuerwehrmann.preName</td>
                            <td>@feuerwehrmann.Geburtsdatum.ToString("dd/ MMMM yyyy")</td>
                            <td>
                                @((ViewBag.Dienstgrade as Dictionary<int, string>)[(Int32)feuerwehrmann.dienstGrad])
                            </td>
                            <td>
                                <a class="btn btn-primary mt-2" asp-controller="Atemschutz" asp-action="FMBefoerdern" asp-route-id=@feuerwehrmann.Id>
                                    Befördern
                                </a>
                                <a class="btn btn-danger mt-2" asp-controller="Atemschutz" asp-action="FMDegradieren" asp-route-id=@feuerwehrmann.Id>
                                    Degradieren
                                </a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

FeuerwehrApp/Views/Atemschutz/Overview.cshtml
@model OverviewViewModel

<h1>Feuerwehr Vasbeck</h1>

<hr />

<div class="row">
    <div class="justify-content-center col d-flex align-items-center">
        <a class="btn btn-primary mt-2 mr-2" asp-controller="Atemschutz" asp-action="CreateEditFM">
            Neuer Feuerwehrmann
        </a>
    </div>
    <div class="justify-content-center col d-flex align-items-center">
    <a class="btn btn-primary mt-2 mr-2" asp-controller="Atemschutz" asp-action="CreateEditAGT">
        Neuer Geräteträger
    </a>
    </div>
    <div class="justify-content-center col d-flex align-items-center">
    <a class="btn btn-primary mt-2" asp-controller="Atemschutz" asp-action="CreateEditLicense">
        Fahrer hinzufügen
    </a>
    </div>
    <div class="justify-content-center col d-flex align-items-center">
        <a class="btn btn-primary mt-2" asp-controller="Atemschutz" asp-action="CreateEditMaske">
            Maske anlegen
        </a>
    </div>
    <div class="justify-content-center col d-flex align-items-center">
        <a class="btn btn-primary mt-2" asp-controller="Atemschutz" asp-action="CreateEditGeraet">
            Gerät anlegen
        </a>
    </div>
</div>
<hr/>
<div>
    <h2>Übersicht der Atemschutzgeräteträger</h2>
    <div class="row">
        <div class="col-md-4">
            <img src="~/Images/agt.png" alt="Geräteträger" class="img-fluid" />
            <div class="justify-content-center col d-flex align-items-center">
                
                <a class="btn btn-secondary mt-2 ml-2" asp-controller="Atemschutz" asp-action="DetailsAGT">
                    Details
                </a>
            </div>
        </div>
        <div class="col-md-8" id="tblAGT">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Vorname</th>
                        <th>Tauglich?</th>
                        <th>Nächstes Ablaufdatum</th>
                        <th>Was?</th>
                        <th>Aktionen</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var agt in Model.AGT)
                    {
                        <tr>
                            <td>@agt.lastName</td>
                            <td>@agt.preName</td>
                            <td>
                                @if (agt.ExpiringDates.Min() >= DateTime.Now)
                                {

                                    <span class="fa fa-check-circle" style="expiring-green">Ja</span>
                                }
                                else
                                {
                                    <span class="fa fa-times-circle" style="expiring-red">Nein</span>
                                }
                            </td>
                            <td style="@(agt.ExpiringDates.Min() <= DateTime.Now ? "expiring-red" :
                 agt.ExpiringDates.Min() <= DateTime.Now.AddMonths(1) ? "expiring-orange" : "expiring-black")">
                                @agt.ExpiringDates.Min().ToString("dd/MM/yyyy")
                            </td>
                            <td>@agt.GetEarliestExpirationField()</td>
                            <td>
                                <a class="btn btn-sm btn-warning" asp-controller="Atemschutz" asp-action="CreateEditAGT" asp-route-id="@agt.Id">Ändern</a>
                                <a class="btn btn-sm btn-danger" asp-controller="Atemschutz" asp-action="DeleteAGT" asp-route-id="@agt.Id">Entfernen</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>
<hr />
<div>
    <h2>Übersicht der Führerscheine</h2>
    <div class="row">
        <div class="col-md-3">
            <img src="~/Images/eu_fe_hinten.jpg" alt="Führerscheine" class="img-fluid" />
            <div class="justify-content-center col d-flex align-items-center">
                
            </div>
        </div>
        <div class="col-md-9" id="tblFuehrerscheine">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Status</th>
                        <th>Name</th>
                        <th>Vorname</th>
                        <th>Klasse</th>
                        <th>Ablaufdatum</th>
                        <th>Prüfdatum</th>
                        <th>Verwendung</th>
                        <th>Aktionen</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var fahrer in Model.DrivingLicenses)
                    {
                        <tr>
                            <td>
                                @{
                                    bool isExpired = fahrer.ExpiringDate <= DateTime.Now;  // Bedingung, die festlegt, ob es abgelaufen ist
                                }
                                <span class="fa fa-check-circle @(isExpired ? "expiring-red" : "expiring-green")">
                                    @(isExpired ? "abgelaufen" : "Ok")
                                </span>
                            </td>
                            <td>@fahrer.lastName</td>
                            <td>@fahrer.preName</td>
                            <td>@fahrer.FSKlasse</td>
                            <td>@fahrer.ExpiringDate.ToString("dd/MM/yyyy")</td>
                            <td>@fahrer.CheckDate.ToString("dd/MM/yyyy")</td>
                            <td>@fahrer.Usage</td>
                            <td>
                                <a class="btn btn-sm btn-warning" asp-controller="Atemschutz" asp-action="CreateEditLicense" asp-route-id="@fahrer.Id">Ändern</a>
                                <a class="btn btn-sm btn-secondary" asp-controller="Atemschutz" asp-action="CheckLicense" asp-route-id="@fahrer.Id">Prüfen</a>
                                <a class="btn btn-sm btn-danger" asp-controller="Atemschutz" asp-action="CreateEditLicense" asp-route-id="@fahrer.Id">Entfernen</a>
                                
                            </td>
                            
                        </tr>
                    }
                </tbody>

            </table>
        </div>
    </div>
</div>
<hr />
<div>
    <h2>Übersicht der Atemschutzmasken</h2>
    <div class="row">
        <div class="col-md-4">
            <img src="~/Images/atemschutzmaske.jpeg" alt="Atemschutzmaske" class="img-fluid" />
            
        </div>
        <div class="col-md-8" id="tblMasken">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Maskennummer</th>
                        <th>Ablaufdatum</th>
                        <th>Personalisiert?</th>
                        <th>Lagerplatz</th>
                        <th>Aktionen</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var atemschutzmaske in Model.Atemschutzmasken)
                    {
                        <tr>
                            <td>@atemschutzmaske.Number</td>
                            <td style="@(atemschutzmaske.ExpiringDate <= DateTime.Now ? "expiring-red" :
                 atemschutzmaske.ExpiringDate <= DateTime.Now.AddMonths(1) ? "expiring-orange" : "expiring-black")">
                                @atemschutzmaske.ExpiringDate.ToString("MM/yyyy")
                            </td>
                            <td>
                                @if (atemschutzmaske.IsPersonalized)
                                {
                                    <i class="fa fa-check-circle" style="color: green;">Ja</i>
                                }
                                else
                                {
                                    <i class="fa fa-times-circle" style="color: red;">Nein</i>
                                }

                            <td>@atemschutzmaske.StoragePlace</td>
                            <td>
                                <a class="btn btn-sm btn-danger" asp-controller="Atemschutz" asp-action="DeleteMaske" asp-route-id="@atemschutzmaske.Id">Maske entfernen</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>
<hr />
<div>
    <h2>Übersicht der Atemschutzgeräte</h2>
    <div class="row">
        <div class="col-md-4">
            <img src="~/Images/atemschutzgeraet.jpg" alt="Atemschutzgerät" class="img-fluid" />
            
        </div>
        <div class="col-md-8" id="tblGeraete">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Gerätenummer</th>
                        <th>Ablaufdatum</th>
                        <th>Aktionen</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var atemschutzgeraet in Model.Atemschutzgeraete)
                    {
                        <tr>
                            <td>@atemschutzgeraet.Number</td>
                            <td style="@(atemschutzgeraet.ExpiringDate <= DateTime.Now ? "expiring-red" :
                 atemschutzgeraet.ExpiringDate <= DateTime.Now.AddMonths(1) ? "expiring-orange" : "expiring-black")">
                                @atemschutzgeraet.ExpiringDate.ToString("MM/yyyy")
                            </td>
                            <td>
                                <a class="btn btn-sm btn-danger" asp-controller="Atemschutz" asp-action="DeleteGeraet" asp-route-id="@atemschutzgeraet.Id">Gerät entfernen</a>
                            </td>
                        </tr>
                    }
                </tbody>

            </table>
        </div>
    </div>
</div>